AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
    Default: "poc-ethers-umbundled"
    Description: "The name of the application"
  StageName:
    Type: String
    Default: "dev"
    Description: "The name of the stage/environment"
  JsonRPCUrl:
    Type: String
    # Default: "https://eth.llamarpc.com"         # Mainnet
    Default: "https://sepolia.drpc.org"           # Sepolia testnet
    # Default: "http://172.17.0.1:8545"           # Localhost node (linux)
    # Default: "http://host.docker.internal:8545" # Localhost node (macOS & Windows)
    Description: "The URL of the JSON-RPC endpoint for the EVM based blockchain network"
  LambdaInsightsLayerVersion:
    Type: String
    Default: "55" # Update this manually when needed
    Description: "The version of the Lambda Insights layer"

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      DefaultRouteSettings:
        ThrottlingRateLimit: 500
        ThrottlingBurstLimit: 500

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs20.x
      CodeUri: ./ # root directory
      MemorySize: 128
      Timeout: 25
      # Tracing: Active
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:${LambdaInsightsLayerVersion}
      Environment:
        Variables:
          STAGE: !Ref StageName
          APP_NAME: !Ref AppName
          JSON_RPC_URL: !Ref JsonRPCUrl
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEventMyLambdaProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref HttpApi
    Metadata:
      BuildMethod: makefile

Outputs:
  ApiGatewayInvokeURL:
    Description: "Invoke URL for the API Gateway"
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/health-check'
    Export:
      Name: !Sub '${AppName}-ApiGatewayInvokeURL-${StageName}'

  MyLambdaFunctionArn:
    Description: "ARN of the deployed Lambda function"
    Value: !GetAtt MyLambdaFunction.Arn
    Export:
      Name: !Sub '${AppName}-MyLambdaFunctionArn-${StageName}'
