version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "poc-ethers-bundled-minified"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
fail_on_empty_changeset = false
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false