# Ref: https://www.serverless.com/framework/docs/providers/aws/events/s3
service: s3-demo

# Load environment variable from ".env"
useDotenv: true

# Custom variables (accessed via ${self:custom.params.VARIABLE_NAME})
custom:
  params:
    # Serverless always loads the leftmost defined value
    # In this case, when param:MEDIA_BUCKET_NAME is not defined, it will load env:MEDIA_BUCKET_NAME
    MEDIA_BUCKET_NAME: ${param:MEDIA_BUCKET_NAME, env:MEDIA_BUCKET_NAME}

# Which files should or should not be packed in the lambda function
package:
  patterns:
    - '!./**' # Exclude all files
    - './src/**' # Include src
    - './node_modules/**' # Include node_modules

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    # Environment variables that will be loaded into the lambda function
    REGION: ${opt:region, 'us-east-1'}
    MEDIA_BUCKET_NAME: ${self:custom.params.MEDIA_BUCKET_NAME}

functions:
  main:
    handler: src/handler.handler
    timeout: 30 # Timeout in seconds
    events:
      - s3: # Trigger the lambda function when an image is uploaded to media bucket
          bucket: ${self:custom.params.MEDIA_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: imgs/
            - suffix: .jpg
          existing: true
      - s3: # Trigger the lambda function when an image is deleted from media bucket
          bucket: ${self:custom.params.MEDIA_BUCKET_NAME}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: imgs/
            - suffix: .jpg
          existing: true
